name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Lint with flake8
      run: |
        pip install flake8
        pip install flake8-docstrings
        # stop the build if there are Python syntax errors or undefined names
        flake8 activity01.py --count --select=E9,F63,F7,F82 --show-source --statistics
        # check that there are docstrings and that line width does not exceed reasonable limit (gh editor limit is 127 chars)
        flake8 assign01.py --count --max-complexity=10 --max-line-length=127 --ignore=D205,D210,D400,D401,E111 --statistics
    - name: Check out test repo
      uses: actions/checkout@v2
      with:
        repository: sgeinitz/cs4050_tests
        path: tests
    - name: Run unit tests
      run: |
        python -m unittest tests/assign01_test.py
